### ISSUE TITLE
Link described as "Basic annotation with suggested overall masking" points to file without masking suggestions 

### ISSUE THREAD

**Issue by ellisifnygaard** [zwdzwd/zwdzwd.github.io#1]
On the [**GRCh37 / hg19** webpage ](http://zwdzwd.github.io/InfiniumAnnotation/EPIC_hm450_hg19.html), it appears that the following file is described as containing *"Basic annotation with suggested overall masking"*:  
https://github.com/zhou-lab/InfiniumAnnotationV1/blob/main/Anno/HM450/HM450.hg19.manifest.tsv.gz 
  
Lines 5-7 in https://github.com/zwdzwd/zwdzwd.github.io/blob/master/InfiniumAnnotation/EPIC_hm450_hg19.html seem to confirm this:
https://github.com/zwdzwd/zwdzwd.github.io/blob/cd980aa1f28ac4bee9c486ba5a5f76012e3bdba2/InfiniumAnnotation/EPIC_hm450_hg19.html#L7  
  
  
However, when I download `HM450.hg19.manifest.tsv.gz` from https://github.com/zhou-lab/InfiniumAnnotationV1/blob/main/Anno/HM450/HM450.hg19.manifest.tsv.gz, I get a file that does not contain any columns pertaining to masking. It has the following column headers:
`CpG_chrm	CpG_beg	CpG_end	address_A	address_B	target	nextBase	channel	Probe_ID	mapFlag_A	mapChrm_A	mapPos_A	mapQ_A	mapCigar_A	AlleleA_ProbeSeq	mapNM_A	mapAS_A	mapYD_A	mapFlag_B	mapChrm_B	mapPos_B	mapQ_B	mapCigar_B	AlleleB_ProbeSeq	mapNM_B	mapAS_B	mapYD_B	type`
, where I would expect to find `MASK_general` etc.  
  
  
Is the lack of masking suggestions deliberate? Which file should I download if I would like the latest general masking suggestions for HM450K GRCh37?

Cheers 😀

**Comment by zwdzwd** [comment]
Thanks for reporting. The file links were wrong for hg19 and is now updated. 
https://github.com/zhou-lab/InfiniumAnnotationV1/raw/main/Anno/HM450/archive/202209/HM450.hg19.manifest.tsv.gz
