### ISSUE TITLE
Some hg38 manifest files have incorrect probe mappings

### ISSUE THREAD

**Issue by CristianBologa** [zwdzwd/zwdzwd.github.io#2]
### Example - probe cg13130526 has different mappings in HM450, EPIC, and EPICv2
**HM450.hg38.manifest.tsv.gz**
```
chr1	148804917	148804919	14626452	NA	CG	NA	NA	cg13130526
```
**EPIC.hg38.manifest.tsv.gz**
```
chr1	149325325	149325327	28680230	NA	CG	NA	NA	cg13130526
```
**EPICv2.hg38.manifest.tsv.gz**
```
chr1	120193486	120193488	36715440	NA	CG	NA	NA	cg13130526_BC21
chr1	120193486	120193488	38723242	NA	CG	NA	NA	cg13130526_BC22
chr1	120193486	120193488	3758989		NA	CG	NA	NA	cg13130526_BC23
```

**Comment by zwdzwd** [comment]
these probes have already been masked for non-unique mapping.

```
cg13130526_BC21 M_nonuniq       M_nonuniq       TRUE
cg13130526_BC22 M_nonuniq       M_nonuniq       TRUE
cg13130526_BC23 M_nonuniq       M_nonuniq       TRUE
```

File source: https://zwdzwd.github.io/InfiniumAnnotation

<img width="516" alt="image" src="https://github.com/zwdzwd/zwdzwd.github.io/assets/7670339/3823a979-03bf-4af4-b059-4439fa90b543">

**Comment by CristianBologa** [comment]
I apologize for not being more explicit:

- in HM450.hg38.manifest.tsv.gz, probe cg13130526 maps to chr1:**148804917-148804919**
- in EPIC.hg38.manifest.tsv.gz, same probe maps to chr1:**149325325-149325327**
- and in EPICv2.hg38.manifest.tsv.gz, it maps to chr1:**120193486-120193488**

How is that possible?

**Comment by zwdzwd** [comment]
Hi, the CG number does not uniquely determine the probe sequence. That's the motivation for introducing the probe suffixes. If the mapping is non-unique, we randomly report one mapping location. We should be cautious interpreting the genomic coordinates, and it is recommended to flag/mask them, which is what those masking files were designed for. Hope this clarifies.
